### ISSUE TITLE
Duplicate modules

### ISSUE THREAD

**Issue by Pandur256** [deGov/features#11]
There're duplicate module names in this "features" category and the "modules" category i.e. degov_media_document, degov_media_image, degov_media_video. Therefore I can't install the features and the modules mod. Are those different modules? What's the distinction for anyway? Would you be so kind to provide information on the topic?

**Comment by iampuma** [comment]
degov/features is deprecated since the deGov release 1.7.0. So which version are you exactly using?

**Comment by Pandur256** [comment]
Interesting! Some sort of documatation would be nice. It's totally confusing since there're six different subfolders for deGov and no comment on which is for what.

So basicly I just need the "modules" and the theme maybe to run deGov?

**Comment by iampuma** [comment]
It was initially chosen when creating deGov to divide project into multiple repositories for our development purposes. The degov/features repository is deprecated since 1.7.0, however kept to preserve backwards compatibility for those who need to update to the new version of deGov. If you are installing deGov from scratch, our recommendation is for now to use the installation profile, which is located here https://github.com/deGov/deGov.

We are taking this as feedback as well, to think about improving documentation for developers.

**Comment by Pandur256** [comment]
Thanks for the info :)

**Comment by iampuma** [comment]
No problem!
